version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "profileDB"
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "postgresql"
    ports:
      - 5432:5432
